/**
 * YouTube Subtitle Extractor
 * Extracts subtitle URLs and metadata from YouTube videos
 */

export interface CaptionTrack {
  baseUrl: string;
  name: {
    simpleText: string;
  };
  languageCode: string;
  kind?: string;
  vssId: string;
  isTranslatable?: boolean;
}

export interface CaptionsData {
  captionTracks?: CaptionTrack[];
  audioTracks?: Array<{
    captionTrackIndices: number[];
    defaultCaptionTrackIndex: number;
    hasDefaultTrack: boolean;
    captionsInitialState: string;
  }>;
  translationLanguages?: Array<{
    languageCode: string;
    languageName: { simpleText: string };
  }>;
}

export interface SubtitleInfo {
  url: string;
  languageCode: string;
  languageName: string;
  isAutoGenerated: boolean;
  isTranslatable: boolean;
  isDefault: boolean;
}

export class YouTubeSubtitleExtractor {
  private cachedPlayerResponse: any = null;
  private lastVideoId: string | null = null;

  /**
   * Get ytInitialPlayerResponse from the page
   */
  private getYtInitialPlayerResponse(): any {
    try {
      // Check if video ID has changed
      const currentVideoId = this.getCurrentVideoId();
      if (currentVideoId !== this.lastVideoId) {
        this.cachedPlayerResponse = null;
        this.lastVideoId = currentVideoId;
      }

      // Return cached if available
      if (this.cachedPlayerResponse) {
        return this.cachedPlayerResponse;
      }

      // Try to get from window object
      const ytInitialPlayerResponse = (window as any).ytInitialPlayerResponse;
      if (ytInitialPlayerResponse) {
        console.log("📊 Found ytInitialPlayerResponse in window");
        this.cachedPlayerResponse = ytInitialPlayerResponse;
        return ytInitialPlayerResponse;
      }

      // Try to parse from page scripts
      const scripts = document.getElementsByTagName("script");
      for (const script of scripts) {
        const content = script.textContent || script.innerText;
        if (content.includes("ytInitialPlayerResponse")) {
          const match = content.match(
            /ytInitialPlayerResponse\s*[:=]\s*({.+?});/
          );
          if (match) {
            console.log("📊 Parsed ytInitialPlayerResponse from script");
            const parsed = JSON.parse(match[1]);
            this.cachedPlayerResponse = parsed;
            return parsed;
          }
        }
      }

      console.log("⚠️ ytInitialPlayerResponse not found");
      return null;
    } catch (error) {
      console.error("❌ Failed to get ytInitialPlayerResponse:", error);
      return null;
    }
  }

  /**
   * Get current video ID from URL
   */
  public getCurrentVideoId(): string | null {
    const urlParams = new URLSearchParams(window.location.search);
    const videoId = urlParams.get('v');
    
    if (!videoId) {
      // Try to get from player response as fallback
      try {
        const playerResponse = (window as any).ytInitialPlayerResponse;
        return playerResponse?.videoDetails?.videoId || null;
      } catch {
        return null;
      }
    }
    
    return videoId;
  }

  /**
   * Get all available caption tracks
   */
  public getCaptionTracks(): CaptionTrack[] {
    const playerResponse = this.getYtInitialPlayerResponse();
    if (!playerResponse || !playerResponse.captions) {
      console.log("No captions data found");
      return [];
    }

    const captionsData: CaptionsData =
      playerResponse.captions.playerCaptionsTracklistRenderer;
    
    if (!captionsData || !captionsData.captionTracks) {
      console.log("No caption tracks found");
      return [];
    }

    console.log(`Found ${captionsData.captionTracks.length} caption tracks`);
    
    // Log caption initial state if available
    if (captionsData.audioTracks && captionsData.audioTracks.length > 0) {
      const audioTrack = captionsData.audioTracks[0];
      console.log("Caption initial state:", audioTrack.captionsInitialState);
      console.log("Default caption track index:", audioTrack.defaultCaptionTrackIndex);
    }

    return captionsData.captionTracks;
  }

  /**
   * Get all available subtitle information
   */
  public getAllSubtitles(): SubtitleInfo[] {
    const captionTracks = this.getCaptionTracks();
    const playerResponse = this.getYtInitialPlayerResponse();
    
    // Get default track index
    let defaultIndex = -1;
    if (playerResponse?.captions?.playerCaptionsTracklistRenderer?.audioTracks?.[0]) {
      defaultIndex = playerResponse.captions.playerCaptionsTracklistRenderer
        .audioTracks[0].defaultCaptionTrackIndex;
    }

    return captionTracks.map((track, index) => ({
      url: track.baseUrl,
      languageCode: track.languageCode,
      languageName: track.name.simpleText,
      isAutoGenerated: track.kind === 'asr' || track.vssId?.includes('.asr'),
      isTranslatable: track.isTranslatable || false,
      isDefault: index === defaultIndex
    }));
  }

  /**
   * Get subtitle URL for specific language
   */
  public getSubtitleUrl(
    languageCode: string,
    options: {
      preferAutoGenerated?: boolean;
      includeTranslations?: boolean;
    } = {}
  ): string | null {
    const captionTracks = this.getCaptionTracks();
    
    if (captionTracks.length === 0) {
      console.log("⚠️ No subtitle tracks available");
      return null;
    }

    // Find exact match
    let track = captionTracks.find(t => 
      t.languageCode === languageCode ||
      t.languageCode.startsWith(languageCode + '-')
    );

    // If no exact match and translations allowed, check translatable tracks
    if (!track && options.includeTranslations) {
      const translatableTrack = captionTracks.find(t => t.isTranslatable);
      if (translatableTrack) {
        // Add translation parameter to URL
        const url = new URL(translatableTrack.baseUrl);
        url.searchParams.set('tlang', languageCode);
        return url.toString();
      }
    }

    if (track) {
      console.log(`✅ Found subtitle: ${track.name.simpleText} (${track.languageCode})`);
      return track.baseUrl;
    }

    console.log(`❌ No subtitle found for language: ${languageCode}`);
    return null;
  }

  /**
   * Get subtitle URLs for multiple languages with priority
   */
  public getSubtitleUrlByPriority(
    preferredLanguages: string[] = ["en", "zh", "zh-CN"]
  ): string | null {
    const captionTracks = this.getCaptionTracks();
    
    if (captionTracks.length === 0) {
      console.log("⚠️ No subtitle tracks available");
      return null;
    }

    // Log all available tracks
    console.log("📋 Available subtitle tracks:", captionTracks.map(track => ({
      language: track.languageCode,
      name: track.name.simpleText,
      vssId: track.vssId,
      isTranslatable: track.isTranslatable
    })));

    // Try to find subtitle by priority
    for (const preferredLang of preferredLanguages) {
      const track = captionTracks.find(
        (track) =>
          track.languageCode === preferredLang ||
          track.languageCode.startsWith(preferredLang + "-") ||
          track.vssId?.includes(preferredLang)
      );

      if (track) {
        console.log(`✅ Selected subtitle: ${track.name.simpleText} (${track.languageCode})`);
        return track.baseUrl;
      }
    }

    // Fallback to first available subtitle
    const firstTrack = captionTracks[0];
    console.log(`🔄 Using default subtitle: ${firstTrack.name.simpleText} (${firstTrack.languageCode})`);
    return firstTrack.baseUrl;
  }

  /**
   * Check if subtitles are available
   */
  public hasSubtitles(): boolean {
    const playerResponse = this.getYtInitialPlayerResponse();
    return !!(
      playerResponse?.captions?.playerCaptionsTracklistRenderer?.captionTracks?.length
    );
  }

  /**
   * Get available translation languages
   */
  public getTranslationLanguages(): Array<{ code: string; name: string }> {
    const playerResponse = this.getYtInitialPlayerResponse();
    const translationLanguages = 
      playerResponse?.captions?.playerCaptionsTracklistRenderer?.translationLanguages;
    
    if (!translationLanguages) {
      return [];
    }

    return translationLanguages.map((lang: any) => ({
      code: lang.languageCode,
      name: lang.languageName.simpleText
    }));
  }

  /**
   * Get video metadata
   */
  public getVideoMetadata() {
    const playerResponse = this.getYtInitialPlayerResponse();
    if (!playerResponse?.videoDetails) {
      return null;
    }

    const details = playerResponse.videoDetails;
    return {
      videoId: details.videoId,
      title: details.title,
      author: details.author,
      channelId: details.channelId,
      duration: parseInt(details.lengthSeconds || '0'),
      viewCount: parseInt(details.viewCount || '0'),
      isLive: details.isLiveContent || false,
      isPrivate: details.isPrivate || false
    };
  }

  /**
   * Generate subtitle URL with custom parameters
   */
  public buildSubtitleUrl(
    baseUrl: string,
    params: {
      format?: 'json3' | 'srv1' | 'srv2' | 'srv3' | 'ttml' | 'vtt';
      translateTo?: string;
      includeTimestamps?: boolean;
    } = {}
  ): string {
    const url = new URL(baseUrl);
    
    // Set format
    if (params.format) {
      url.searchParams.set('fmt', params.format);
    }
    
    // Set translation
    if (params.translateTo) {
      url.searchParams.set('tlang', params.translateTo);
    }
    
    // Include timestamps (for some formats)
    if (params.includeTimestamps !== undefined) {
      url.searchParams.set('ts', params.includeTimestamps ? '1' : '0');
    }
    
    return url.toString();
  }

  /**
   * Reset cache (useful when navigating to new video)
   */
  public resetCache(): void {
    this.cachedPlayerResponse = null;
    this.lastVideoId = null;
  }

  /**
   * Get all subtitle data as a structured object
   */
  public getSubtitleData() {
    const hasSubtitles = this.hasSubtitles();
    
    if (!hasSubtitles) {
      return {
        available: false,
        subtitles: [],
        translationLanguages: [],
        metadata: this.getVideoMetadata()
      };
    }

    return {
      available: true,
      subtitles: this.getAllSubtitles(),
      translationLanguages: this.getTranslationLanguages(),
      metadata: this.getVideoMetadata()
    };
  }
}