/**
 * YouTube Subtitle Extractor
 * Extracts subtitle URLs and metadata from YouTube videos
 */

export interface CaptionTrack {
  baseUrl: string;
  name: {
    simpleText: string;
  };
  languageCode: string;
  kind?: string;
  vssId: string;
  isTranslatable?: boolean;
}

export interface CaptionsData {
  captionTracks?: CaptionTrack[];
  audioTracks?: Array<{
    captionTrackIndices: number[];
    defaultCaptionTrackIndex: number;
    hasDefaultTrack: boolean;
    captionsInitialState: string;
  }>;
  translationLanguages?: Array<{
    languageCode: string;
    languageName: { simpleText: string };
  }>;
}

export interface SubtitleInfo {
  url: string;
  languageCode: string;
  languageName: string;
  isAutoGenerated: boolean;
  isTranslatable: boolean;
  isDefault: boolean;
}

export interface SubtitleTrack {
  languageCode: string;
  kind?: "asr" | "default" | "manual";
  name?: string;
  params: Map<string, string>;
}

export interface YouTubeCaptionTrack {
  languageCode: string;
  languageName: string;
  kind: string;
  name: string;
  displayName: string;
  id: string | null;
  W: boolean;
  isTranslateable: boolean;
  url: string;
  vssId: string;
  isDefault: boolean;
  translationLanguage: string | null;
  xtags: string;
  captionId: string;
}

export interface YouTubeSubtitleTrackData {
  id: string;
  d7: {
    name: string;
    id: string;
    isDefault: boolean;
  };
  captionTracks: YouTubeCaptionTrack[];
  J: any;
  B: YouTubeCaptionTrack;
  xtags: string;
  N: boolean;
  W: any;
  Z: string;
  captionsInitialState: string;
}
export interface YouTubeYtcfg {
  INNERTUBE_CLIENT_VERSION: string;
}

export class YouTubeSubtitleExtractor {
  /**
   * 动态加载扩展内的脚本，并等待脚本触发指定事件返回结果
   * @param scriptName 脚本文件名，例如 "youtube_meta.js"
   * @returns Promise<any> 脚本返回的数据
   */
  public loadExtensionScript(scriptName: string): Promise<any> {
    return new Promise((resolve, reject) => {
      // 自定义事件名称
      const eventName = "grab_youtube_metacontext_youmind";

      // 事件处理函数
      const handler = (event: CustomEvent) => {
        window.removeEventListener(eventName, handler as EventListener);
        resolve(event.detail); // 脚本通过 event.detail 传递结果
      };

      // 监听事件
      window.addEventListener(eventName, handler as EventListener);

      try {
        // 创建 <script> 标签
        const script = document.createElement("script");

        // 扩展内部文件完整 URL
        script.src = chrome.runtime.getURL(`./scripts/${scriptName}`);
        console.log(script.src);
        // 加载完成后删除 <script>
        script.onload = () => script.remove();

        // 加载失败回调
        script.onerror = (err) => reject(err);

        // 插入 DOM 触发浏览器加载
        (document.head || document.documentElement).appendChild(script);
      } catch (err) {
        reject(err);
      }
    });
  }
  /**
   * Get subtitle track data using extension script
   */
  public async getSubtitleTrack(): Promise<{
    currentTrack: YouTubeSubtitleTrackData;
    ytcfg: YouTubeYtcfg;
  } | null> {
    try {
      const trackData = (await this.loadExtensionScript(
        "inject-youtube.js"
      )) as { currentTrack: YouTubeSubtitleTrackData; ytcfg: YouTubeYtcfg };
      return trackData;
    } catch (error) {
      console.error("Failed to get subtitle track data:", error);
      return null;
    }
  }

  /**
   * Get subtitle URL for specific language
   */
  public async getSubtitleUrl(
    languageCode: string,
    options: {
      preferAutoGenerated?: boolean;
      includeTranslations?: boolean;
    } = {}
  ): Promise<string | null> {
    try {
      const trackData = await this.getSubtitleTrack();
      console.log(trackData);
      if (!trackData || !trackData.currentTrack?.captionTracks) {
        return null;
      }

      const matchingTracks = trackData.currentTrack.captionTracks.filter(
        (track) => track.languageCode === languageCode
      );

      if (matchingTracks.length === 0) {
        return null;
      }

      let selectedTrack: YouTubeCaptionTrack | null = null;

      // Priority 1: name="Default" and empty kind
      const defaultTrack = matchingTracks.find(
        (track) => track.name === "Default" && track.kind === ""
      );
      if (defaultTrack) {
        selectedTrack = defaultTrack;
      } else {
        // Priority 2: kind="asr" (auto-generated)
        const asrTrack = matchingTracks.find((track) => track.kind === "asr");
        if (asrTrack) {
          selectedTrack = asrTrack;
        } else {
          // Fallback: first matching track
          selectedTrack = matchingTracks[0];
        }
      }

      if (!selectedTrack) {
        return null;
      }

      // Append required parameters to the URL
      const baseUrl = selectedTrack.url;
      const additionalParams = new URLSearchParams({
        fmt: "json3",
        xorb: "2",
        xobt: "3",
        xovt: "3",
        cbr: "Chrome",
        cbrver: "131.0.0.0",
        c: "WEB",
        cver: trackData.ytcfg?.INNERTUBE_CLIENT_VERSION || "2.20250908.02.00",
        cplayer: "UNIPLAYER",
        cos: "Windows",
        cosver: "10.0",
        cplatform: "DESKTOP",
      });

      const separator = baseUrl.includes("?") ? "&" : "?";
      return `${baseUrl}${separator}${additionalParams.toString()}`;
    } catch (error) {
      console.error("Failed to get subtitle URL:", error);
      return null;
    }
  }
}
